# Generated by Django 2.0.1 on 2018-02-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('language', models.CharField(blank=True, max_length=5, null=True)),
                ('name', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('semester', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'course_implementation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'curriculum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('seat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupCourseImplementation',
            fields=[
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='schedule.Group')),
            ],
            options={
                'db_table': 'group_course_implementation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherCourseImplementation',
            fields=[
                ('teacherid', models.ForeignKey(db_column='teacherid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='schedule.Teacher')),
                ('p1', models.IntegerField(blank=True, null=True)),
                ('p2', models.IntegerField(blank=True, null=True)),
                ('p3', models.IntegerField(blank=True, null=True)),
                ('p4', models.IntegerField(blank=True, null=True)),
                ('p5', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teacher_course_implementation',
                'managed': False,
            },
        ),
    ]
